from app import *
from marshmallow import Schema, fields


class HRDRequest(Schema):
   lname= fields.Str(default="NY")
   tname=fields.Str(default="plate_type")
   address=fields.Str(dafault="10, ABC , Street-1 DEF-110003")
   leaseperiod=fields.Str(default="1 year")
   fromDt=fields.Str(default="1-09-2024")
   to=fields.Str(default="1-09-2024")
   monthlyrent=fields.Str(default="30000")
   deposit=fields.Str(default="100000") 

class Seller(Schema):
   seller_name=fields.Str(default='')
   seller_fathhus=fields.Str(default='')
   seller_age=fields.Str(default='')
   seller_pan=fields.Str(default='')
   seller_caste=fields.Str(default='')
   seller_address=fields.Str(default='')

class Purchaser(Schema):
   purchaser_name=fields.Str(default='')
   purchaser_father=fields.Str(default='')
   purchaser_age=fields.Str(default='')
   purchaser_caste=fields.Str(default='')
   purchaser_pan=fields.Str(default='')
   purchaser_address=fields.Str(default='')
   
class SDDRequest(Schema):
   day=fields.Str(default='')
   month=fields.Str(default='')
   year=fields.Str(default='')
   sellers=fields.List(fields.Nested(Seller),required=True)
   purchasers=fields.List(fields.Nested(Purchaser),required=True)
   type_of_property=fields.Str(default='')
   land=fields.Str(default='')
   land_size=fields.Str(default='')
   rs_plotnum=fields.Str(default='')
   lr_plotnum=fields.Str(default='')
   rs_khaitnanum=fields.Str(default='')
   lr_khaitannum=fields.Str(default='')
   moza=fields.Str(default='')
   jlnum=fields.Str(default='')
   touzinum=fields.Str(default='')
   policastation=fields.Str(default='')
   subdistrict=fields.Str(default='')
   district=fields.Str(default='')
   flatnumber=fields.Str(default='')
   floorno=fields.Str(default='')
   society=fields.Str(default='')
   division=fields.Str(default='')
   corporation=fields.Str(default='')
   road=fields.Str(default='')
   location=fields.Str(default='')
   supersqfeet=fields.Str(default='')
   landsqfeet=fields.Str(default='')
   percentage=fields.Str(default='')
   previous_owner=fields.Str(default='')
   father_previous_owner=fields.Str(default='')
   father_previous_owner_det=fields.Str(default='')
   previous_sale_deed=fields.Str(default='')
   reg_office=fields.Str(default='')
   volume=fields.Str(default='')
   frompage=fields.Str(default='')
   topage=fields.Str(default='')
   beingno=fields.Str(default='')
   year_prev_saledeed=fields.Str(default='')
   inestate=fields.Str(default='')
   seller_father_deathdate=fields.Str(default='')
   amount=fields.Str(default='')
   amount_in_words=fields.Str(default='')
   agreement_date=fields.Str(default='')
   recieved_money=fields.Str(default='')
   property_handover_date=fields.Str(default='')
   onNorth=fields.Str(default='')
   onSouth=fields.Str(default='')
   onEast=fields.Str(default='')
   onWest=fields.Str(default='')
   witness1=fields.Str(default='')
   witness2=fields.Str(default='')
   seller_type=fields.Str(default='')
   purchaser_type=fields.Str(default='')
   seller_builder_name=fields.Str(default='')
   seller_builder_reg_num=fields.Str(default='')
   seller_builder_fulladdress=fields.Str(default='')
   purchaser_builder_name=fields.Str(default='')
   purchaser_builder_reg_num=fields.Str(default='')
   purchaser_builder_fulladdress=fields.Str(default='')

class PSRRequest(Schema):
   agreement_date=fields.Str(default='')
   parking_amount=fields.Str(default='')
   effective_date=fields.Str(default='')
   seller_name=fields.Str(default='')
   lessor=fields.Str(default='')
   lessee=fields.Str(default='')
   parking_adress=fields.Str(default='')
   payment_method=fields.Str(default='')
   payment_day=fields.Str(default='')
   notice_period=fields.Str(default='')

class APIResponse(Schema):
   message=fields.String(default="")